--- #Testing the J2 module
- hosts: apacheweb:appserver
  user: henry
  connection: ssh
  become: yes
  gather_facts: yes
  vars:
    userName: test
    passWord: test123
    connectionType: SFTP
  tasks:
    - name: Install the conf file customized for the system
      template: src=test.conf.j2 dest=/home/henry/test.conf owner=henry group=henry mode=750
