- name: Restart Apache2
  service: name={{ debian_apache }} state=restarted
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
- name: Restart Httpd
  service: name={{ redhat_apache }} state=restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
- name: InstallTelnet
  yum: name=telnet state=latest

