--- #Full yml playbook
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify the pkg is installed
      raw: dpkg --get-selections | grep telnet > /home/henry/log/pkg.log
