--- # Lookup Playbook for Ansible
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add list of users
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3  
 
