--- # My First YAML Playbook for Ansible
- hosts: apacheweb
  user: henry
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
  tasks:
    - name: Install Lynx 
      action: apt name=lynx state=latest
    - name: Check if vim installed
      action: apt name=vim state=present

