--- # My First YAML Playbook for Ansible
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_prompt:
    - name: pkg_name
      prompt: Install which Package
      default: telnet
      private: no
  tasks:
    - name: Install {{ pkg_name }}
      apt: name={{ pkg_name }} state=latest
  handlers:
    - name: Restart apache
      action: service name=apache2 state=restarted
