--- # My First YAML Playbook for Ansible
- hosts: all
  user: henry
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_version: 0.1b
  tasks:
    - name: Remove apache test packages from UBUNTU
      apt: name=apache2 state=removed
      when: "ansible_os_family == 'Debian'"
      ignore_errors: yes
    - name: Remove HTTPD test packages from Centos
      yum: name=httpd state=removed
      when: "ansible_os_family == 'RedHat'"
      ignore_errors: yes
    - name: Remove lynx test packages U
      apt:  name=lynx state=removed
      when: "ansible_os_family == 'Debian'"
      ignore_errors: yes
    - name: Remove lynx packages from CentOs
      yum: name=lynx state=removed
      when: "ansible_os_family == 'RedHat'"
      ignore_errors: yes
    - name: Remove telnet packages from ubuntu
      apt: name=telnet state=removed
      when: "ansible_os_family == 'Debian'"
      ignore_errors: yes
    - name: Remove telnet packages from CenTos
      yum: name=telnet state=removed
      when: "ansible_os_family == 'RedHat'"
      ignore_errors: yes
