--- # Outline to playbook translation
- hosts: apacheweb # the hosts group
  user: henry # the user which we gonna use
  become: yes # use sudo permissions
  gather_facts: no # stop from gathering facts

  tasks:
  - name: Create folders
    raw: mkdir -p /home/henry/log
  - name: Date Stamp # date/time stamp for when the playbook starts
    command: /bin/date
    register: timestamp_start
  - debug: var=timestamp_start #    raw: /bin/date > /home/henry/log/playbook.log

  - name: install apache webserver
    apt: pkg=apache2 state=latest
  - name: start the web service
    service: name=apache2 state=restarted
    notify: start HTTPD
  - name: verify the web service is running
    command: service apache2 status
    register: result
  - debug: var=result

  - name: install telnet client software
    apt: name=telnet state=installed
  - name: install lynx client software
    apt: name=lynx state=installed

  - name: log all the packages install on the system
    command: apt list --installed
    register: install_list
  - debug: var=install_list
 
  - name: date/time stamp for when the playbook ends
    command: /bin/date
    register: timestamp_end
  - debug: var=timestamp_end #   raw: /bin/date >> /home/henry/log/playbook.log  

  handlers:
  - name: start HTTPD
    service: name=apache2 state=restarted     
