--- # When Playbook for Ansible
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apace to the Dist Type (Ubuntu)
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: Install Apace to the Dist Type (Redhat)
      command: apt-get -y install httpd
      when: ansible_os_family == "Redhat"
 
